const Books=[
  {
    "author": 'Chinua Achebe',
    "country": 'Nigeria',
    "imageLink": 'images/things-fall-apart.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/Things_Fall_Apart',
    "pages": 209,
    "title": 'Things Fall Apart',
    "year": 1958,
    "id": 0,
    "description": "Written by Chinua Achebe, 'Things Fall Apart' is a novel that explores the life of Okonkwo, a respected warrior and leader of the Igbo people in pre-colonial Nigeria. The book delves into themes of colonialism, cultural clash, and the impact of change on traditional societies."
  },
  {
    "author": 'Hans Christian Andersen',
    "country": 'Denmark',
    "imageLink": 'images/fairy-tales.jpg',
    "language": 'Danish',
    "link": 'https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.',
    "pages": 784,
    "title": 'Fairy tales',
    "year": 1836,
    "id": 1,
    "description": "A collection of enchanting and imaginative stories, 'Fairy tales' have been passed down through generations, captivating readers with magical creatures, moral lessons, and timeless narratives of good versus evil. This genre includes classic tales like 'Cinderella,' 'Snow White,' and 'Hansel and Gretel.'"
  },
  {
    "author": 'Dante Alighieri',
    "country": 'Italy',
    "imageLink": 'images/the-divine-comedy.jpg',
    "language": 'Italian',
    "link": 'https://en.wikipedia.org/wiki/Divine_Comedy',
    "pages": 928,
    "title": 'The Divine Comedy',
    "year": 1315,
    "id": 2,
    "description": "Written by Dante Alighieri, 'The Divine Comedy' is an epic poem that takes readers on a journey through Hell (Inferno), Purgatory (Purgatorio), and Paradise (Paradiso). It explores themes of sin, redemption, and the divine, offering a profound reflection on human nature and the afterlife."
  },
  {
    "author": 'Unknown',
    "country": 'Sumer and Akkadian Empire',
    "imageLink": 'images/the-epic-of-gilgamesh.jpg',
    "language": 'Akkadian',
    "link": 'https://en.wikipedia.org/wiki/Epic_of_Gilgamesh',
    "pages": 160,
    "title": 'The Epic Of Gilgamesh',
    "year": -1700,
    "id": 3,
    "description": "Considered one of the oldest surviving works of literature, 'The Epic of Gilgamesh' is an ancient Mesopotamian poem that follows the adventures of Gilgamesh, a legendary king. It explores themes of mortality, friendship, and the quest for immortality, providing insights into early human civilizations."
  },
  {
    "author": 'Unknown',
    "country": 'Achaemenid Empire',
    "imageLink": 'images/the-book-of-job.jpg',
    "language": 'Hebrew',
    "link": 'https://en.wikipedia.org/wiki/Book_of_Job',
    "pages": 176,
    "title": 'The Book Of Job',
    "year": -600,
    "id": 4,
    "description": "'The Book of Job' is a biblical text that grapples with the problem of human suffering. It tells the story of Job, a righteous man who experiences immense tragedy and engages in philosophical discussions about the nature of God, justice, and the meaning of life."
  },
  {
    "author": 'Unknown',
    "country": 'India/Iran/Iraq/Egypt/Tajikistan',
    "imageLink": 'images/one-thousand-and-one-nights.jpg',
    "language": 'Arabic',
    "link": 'https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights',
    "pages": 288,
    "title": 'One Thousand and One Nights',
    "year": 1200,
    "id": 5,
    "description": "Also known as 'Arabian Nights,' this collection of Middle Eastern folk tales features captivating stories like 'Aladdin's Wonderful Lamp,' 'Ali Baba and the Forty Thieves,' and 'Sinbad the Sailor.' These tales, narrated by Scheherazade to her king, offer a rich tapestry of adventure, fantasy, and moral lessons."
  },
  {
    "author": 'Unknown',
    "country": 'Iceland',
    "imageLink": 'images/njals-saga.jpg',
    "language": 'Old Norse',
    "link": 'https://en.wikipedia.org/wiki/Nj%C3%A1ls_saga',
    "pages": 384,
    "title": "Njál's Saga",
    "year": 1350,
    "id": 6,
    "description": "'Njál's Saga' is an Icelandic saga that depicts the lives of complex and interconnected characters in medieval Iceland. It explores themes of honor, feuds, and the intricacies of interpersonal relationships, providing a vivid portrayal of Viking culture and society."
  },
  {
    "author": 'Jane Austen',
    "country": 'United Kingdom',
    "imageLink": 'images/pride-and-prejudice.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/Pride_and_Prejudice',
    "pages": 226,
    "title": 'Pride and Prejudice',
    "year": 1813,
    "id": 7,
    "description": "Written by Jane Austen, 'Pride and Prejudice' is a classic novel set in 19th-century England. It follows the story of Elizabeth Bennet as she navigates societal expectations, love, and marriage. The book offers a satirical commentary on the manners and customs of the time, while also exploring themes of class, reputation, and self-discovery."
  },
  {
    "author": 'Honoré de Balzac',
    "country": 'France',
    "imageLink": 'images/le-pere-goriot.jpg',
    "language": 'French',
    "link": 'https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot',
    "pages": 443,
    "title": 'Le Père Goriot',
    "year": 1835,
    "id": 8,
    "description": "Penned by Honoré de Balzac, 'Le Père Goriot' is a French novel set in early 19th-century Paris. It tells the tale of Goriot, a loving father who sacrifices everything for his two daughters. The book explores themes of social ambition, wealth, and the corrosive power of society."
  },
  {
    "author": 'Samuel Beckett',
    "country": 'Republic of Ireland',
    "imageLink": 'images/molloy-malone-dies-the-unnamable.jpg',
    "language": 'French, English',
    "link": 'https://en.wikipedia.org/wiki/Molloy_(novel)',
    "pages": 256,
    "title": 'Molloy, Malone Dies, The Unnamable, the trilogy',
    "year": 1952,
    "id": 9,
    "description": "Comprising three interconnected novels, 'Molloy,' 'Malone Dies,' and 'The Unnamable,' this trilogy is written by Samuel Beckett, one of the most influential playwrights and writers of the 20th century. The books employ a unique narrative style and delve into themes of identity, existence, and the limitations of language."
  },
  {
    "author": 'Jorge Luis Borges',
    "country": 'Argentina',
    "imageLink": 'images/ficciones.jpg',
    "language": 'Spanish',
    "link": 'https://en.wikipedia.org/wiki/Ficciones',
    "pages": 224,
    "title": 'Ficciones',
    "year": 1965,
    "id": 10,
    "description": "Written by Jorge Luis Borges, 'Ficciones' is a collection of mind-bending short stories that blur the lines between reality, imagination, and literature itself. With intricate narratives and complex themes such as infinity, labyrinths, and mirrors, Borges challenges traditional storytelling conventions and explores the nature of fiction."
  },
  {
    "author": 'Emily Brontë',
    "country": 'United Kingdom',
    "imageLink": 'images/wuthering-heights.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/Wuthering_Heights',
    "pages": 342,
    "title": 'Wuthering Heights',
    "year": 1847,
    "id": 11,
    "description": "Penned by Emily Brontë, 'Wuthering Heights' is a Gothic novel that revolves around the passionate and tumultuous love story between Catherine Earnshaw and Heathcliff. The book explores themes of love, revenge, social class, and the destructive power of obsession, all set against the atmospheric backdrop of the Yorkshire moors."
  },
  {
    "author": 'Albert Camus',
    "country": 'Algeria, French Empire',
    "imageLink": 'images/l-etranger.jpg',
    "language": 'French',
    "link": 'https://en.wikipedia.org/wiki/The_Stranger_(novel)',
    "pages": 185,
    "title": 'The Stranger',
    "year": 1942,
    "id": 12,
    "description": "Written by Albert Camus, 'The Stranger' is a philosophical novel that follows the life of Meursault, an emotionally detached and indifferent man. The book delves into themes of existentialism, absurdism, and the search for meaning in an indifferent universe, making it a cornerstone of 20th-century literature."
  },
  {
    "author": 'Paul Celan',
    "country": 'Romania, France',
    "imageLink": 'images/poems-paul-celan.jpg',
    "language": 'German',
    "link": '',
    "pages": 320,
    "title": 'Poems',
    "year": 1952,
    "id": 13,
    "description": "The term 'Poems' encompasses a wide array of poetic works, ranging from classical to contemporary. Poems often explore a range of emotions, experiences, and themes through the creative and rhythmic use of language, offering unique insights into the human condition and the beauty of words."
  },
  {
    "author": 'Louis-Ferdinand Céline',
    "country": 'France',
    "imageLink": 'images/voyage-au-bout-de-la-nuit.jpg',
    "language": 'French',
    "link": 'https://en.wikipedia.org/wiki/Journey_to_the_End_of_the_Night',
    "pages": 505,
    "title": 'Journey to the End of the Night',
    "year": 1932,
    "id": 14,
    "description": "Written by Louis-Ferdinand Céline, 'Journey to the End of the Night' is a novel that follows the life of Ferdinand Bardamu as he journeys through war-torn Europe, colonial Africa, and the United States. The book offers a darkly satirical and cynical portrayal of the human condition, war, and society."
  },
  {
    "author": 'Miguel de Cervantes',
    "country": 'Spain',
    "imageLink": 'images/don-quijote-de-la-mancha.jpg',
    "language": 'Spanish',
    "link": 'https://en.wikipedia.org/wiki/Don_Quixote',
    "pages": 1056,
    "title": 'Don Quijote De La Mancha',
    "year": 1610,
    "id": 15,
    "description": "Written by Miguel de Cervantes, 'Don Quijote De La Mancha' is a renowned Spanish novel that tells the story of Alonso Quixano, an aging nobleman who becomes obsessed with chivalric romances and decides to become a knight-errant named Don Quixote. The book is celebrated for its humor, wit, and exploration of reality and illusion."
  },
  {
    "author": 'Geoffrey Chaucer',
    "country": 'England',
    "imageLink": 'images/the-canterbury-tales.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/The_Canterbury_Tales',
    "pages": 544,
    "title": 'The Canterbury Tales',
    "year": 1450,
    "id": 16,
    "description": "Penned by Geoffrey Chaucer, 'The Canterbury Tales' is a collection of stories told by a diverse group of pilgrims traveling to the shrine of Thomas Becket in Canterbury, England. The tales represent a cross-section of medieval society and explore various themes, including love, morality, and human nature."
  },
  {
    "author": 'Anton Chekhov',
    "country": 'Russia',
    "imageLink": 'images/stories-of-anton-chekhov.jpg',
    "language": 'Russian',
    "link": 'https://en.wikipedia.org/wiki/List_of_short_stories_by_Anton_Chekhov',
    "pages": 194,
    "title": 'Stories',
    "year": 1886,
    "id": 17,
    "description": "The term 'Stories' encompasses a broad range of narrative works, including short stories and anthologies, each offering unique and captivating tales. These stories can span various genres, themes, and styles, providing readers with diverse and engaging literary experiences."
  },
  {
    "author": 'Joseph Conrad',
    "country": 'United Kingdom',
    "imageLink": 'images/nostromo.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/Nostromo',
    "pages": 320,
    "title": 'Nostromo',
    "year": 1904,
    "id": 18,
    "description": "Written by Joseph Conrad, 'Nostromo' is a novel set in the fictional South American country of Costaguana. It explores themes of imperialism, political upheaval, and the corrupting influence of power through the story of the eponymous protagonist, Nostromo. The book is known for its intricate narrative structure and psychological depth."
  },
  {
    "author": 'Charles Dickens',
    "country": 'United Kingdom',
    "imageLink": 'images/great-expectations.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/Great_Expectations',
    "pages": 194,
    "title": 'Great Expectations',
    "year": 1861,
    "id": 19,
    "description": "Written by Charles Dickens, 'Great Expectations' follows the life of Pip, an orphan who aspires to become a gentleman after a mysterious benefactor alters the course of his life. The novel explores themes of ambition, social class, morality, and the transformative power of love and compassion."
  },
  {
    "author": 'Denis Diderot',
    "country": 'France',
    "imageLink": 'images/jacques-the-fatalist.jpg',
    "language": 'French',
    "link": 'https://en.wikipedia.org/wiki/Jacques_the_Fatalist',
    "pages": 596,
    "title": 'Jacques the Fatalist',
    "year": 1796,
    "id": 20,
    "description": "Penned by Denis Diderot, 'Jacques the Fatalist' is a philosophical novel that centers around Jacques and his loyal servant as they embark on a series of misadventures. The book challenges traditional narrative conventions, explores themes of fate, free will, and determinism, and employs a playful and digressive storytelling style."
  },
  {
    "author": 'Alfred Döblin',
    "country": 'Germany',
    "imageLink": 'images/berlin-alexanderplatz.jpg',
    "language": 'German',
    "link": 'https://en.wikipedia.org/wiki/Berlin_Alexanderplatz',
    "pages": 600,
    "title": 'Berlin Alexanderplatz',
    "year": 1929,
    "id": 21,
    "description": "Written by Alfred Döblin, 'Berlin Alexanderplatz' is a novel set in 1920s Berlin. It follows the life of Franz Biberkopf, an ex-convict trying to reintegrate into society while navigating the turbulent social and political landscape of the Weimar Republic. The book explores themes of crime, fate, and the allure of the city."
  },
  {
    "author": 'Fyodor Dostoevsky',
    "country": 'Russia',
    "imageLink": 'images/crime-and-punishment.jpg',
    "language": 'Russian',
    "link": 'https://en.wikipedia.org/wiki/Crime_and_Punishment',
    "pages": 551,
    "title": 'Crime and Punishment',
    "year": 1866,
    "id": 22,
    "description": "Written by Fyodor Dostoevsky, 'Crime and Punishment' tells the story of Rodion Raskolnikov, a poor ex-student who commits a murder to test his theory that extraordinary individuals are exempt from moral constraints. The novel explores themes of guilt, redemption, and the psychological turmoil of its complex protagonist."
  },
  {
    "author": 'Fyodor Dostoevsky',
    "country": 'Russia',
    "imageLink": 'images/the-idiot.jpg',
    "language": 'Russian',
    "link": 'https://en.wikipedia.org/wiki/The_Idiot',
    "pages": 656,
    "title": 'The Idiot',
    "year": 1869,
    "id": 23,
    "description": "Penned by Fyodor Dostoevsky, 'The Idiot' portrays the life of Prince Myshkin, an innocent and compassionate man who is often misunderstood by society due to his naivety. The novel delves into themes of morality, love, and the inherent flaws and contradictions of human nature."
  },
  {
    "author": 'Fyodor Dostoevsky',
    "country": 'Russia',
    "imageLink": 'images/the-possessed.jpg',
    "language": 'Russian',
    "link": 'https://en.wikipedia.org/wiki/Demons_(Dostoyevsky_novel)',
    "pages": 768,
    "title": 'The Possessed',
    "year": 1872,
    "id": 24,
    "description": "Also known as 'Demons,' 'The Possessed' is a novel by Fyodor Dostoevsky that explores political and philosophical ideas through the lens of a group of radical revolutionaries. The book examines themes of nihilism, fanaticism, and the destructive consequences of ideological extremism."
  },
  {
    "author": 'Fyodor Dostoevsky',
    "country": 'Russia',
    "imageLink": 'images/the-brothers-karamazov.jpg',
    "language": 'Russian',
    "link": 'https://en.wikipedia.org/wiki/The_Brothers_Karamazov',
    "pages": 824,
    "title": 'The Brothers Karamazov',
    "year": 1880,
    "id": 25,
    "description": "Written by Fyodor Dostoevsky, 'The Brothers Karamazov' is a masterpiece that delves into complex themes such as morality, faith, and the nature of evil. Through the story of the Karamazov family and the trial of Dmitry Karamazov, the novel explores the depths of human psychology and the search for spiritual truth."
  },
  {
    "author": 'George Eliot',
    "country": 'United Kingdom',
    "imageLink": 'images/middlemarch.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/Middlemarch',
    "pages": 800,
    "title": 'Middlemarch',
    "year": 1871,
    "id": 26,
    "description": "Written by George Eliot, 'Middlemarch' is a novel set in the fictional English town of Middlemarch. It weaves together the lives and relationships of various characters, offering a comprehensive and nuanced portrayal of provincial society in the 19th century. The book explores themes of marriage, ambition, and social change."
  },
  {
    "author": 'Ralph Ellison',
    "country": 'United States',
    "imageLink": 'images/invisible-man.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/Invisible_Man',
    "pages": 581,
    "title": 'Invisible Man',
    "year": 1952,
    "id": 27,
    "description": "Written by Ralph Ellison, 'Invisible Man' is a novel that explores the African American experience and identity in the United States. The book follows an unnamed protagonist as he grapples with racism, prejudice, and his own invisibility in a society that refuses to see him as an individual. It delves into themes of self-discovery, social alienation, and the search for personal identity."
  },
  {
    "author": 'Euripides',
    "country": 'Greece',
    "imageLink": 'images/medea.jpg',
    "language": 'Greek',
    "link": 'https://en.wikipedia.org/wiki/Medea_(play)',
    "pages": 104,
    "title": 'Medea',
    "year": -431,
    "id": 28,
    "description": "Written by Euripides, 'Medea' is a Greek tragedy that tells the story of Medea, a powerful sorceress and former princess who seeks revenge against her husband, Jason. The play explores themes of betrayal, vengeance, and the position of women in society, presenting a complex and compelling portrayal of a tragic anti-heroine."
  },
  {
    "author": 'William Faulkner',
    "country": 'United States',
    "imageLink": 'images/absalom-absalom.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/Absalom,_Absalom!',
    "pages": 313,
    "title": 'Absalom, Absalom!',
    "year": 1936,
    "id": 29,
    "description": "Penned by William Faulkner, 'Absalom, Absalom!' is a novel that delves into the complex history of the South, particularly the rise and fall of the Sutpen family. The book explores themes of race, slavery, and the interplay between personal and collective memory, offering a challenging and intricate narrative structure."
  },
  {
    "author": 'William Faulkner',
    "country": 'United States',
    "imageLink": 'images/the-sound-and-the-fury.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/The_Sound_and_the_Fury',
    "pages": 326,
    "title": 'The Sound and the Fury',
    "year": 1929,
    "id": 30,
    "description": "Written by William Faulkner, 'The Sound and the Fury' is a modernist novel that employs multiple narrators and non-linear storytelling techniques. The book explores the decline of the Compson family and delves into themes of time, memory, and the disintegration of traditional Southern values."
  },
  {
    "author": 'Gustave Flaubert',
    "country": 'France',
    "imageLink": 'images/madame-bovary.jpg',
    "language": 'French',
    "link": 'https://en.wikipedia.org/wiki/Madame_Bovary',
    "pages": 528,
    "title": 'Madame Bovary',
    "year": 1857,
    "id": 31,
    "description": "Written by Gustave Flaubert, 'Madame Bovary' tells the story of Emma Bovary, a young woman trapped in a loveless marriage and yearning for passion and excitement. The novel explores themes of romanticism, adultery, and the consequences of pursuing unrealistic ideals in a society constrained by conventions."
  },
  {
    "author": 'Gustave Flaubert',
    "country": 'France',
    "imageLink": 'images/l-education-sentimentale.jpg',
    "language": 'French',
    "link": 'https://en.wikipedia.org/wiki/Sentimental_Education',
    "pages": 606,
    "title": 'Sentimental Education',
    "year": 1869,
    "id": 32,
    "description": "Penned by Gustave Flaubert, 'Sentimental Education' follows the life of Frédéric Moreau, a young man of limited means, as he navigates love affairs, political upheaval, and the shifting social landscape of mid-19th-century France. The book explores themes of idealism, disillusionment, and the complexities of human relationships."
  },
  {
    "author": 'Federico García Lorca',
    "country": 'Spain',
    "imageLink": 'images/gypsy-ballads.jpg',
    "language": 'Spanish',
    "link": 'https://en.wikipedia.org/wiki/Gypsy_Ballads',
    "pages": 218,
    "title": 'Gypsy Ballads',
    "year": 1928,
    "id": 33,
    "description": "Also known as 'Romancero Gitano,' 'Gypsy Ballads' is a collection of poems by Federico García Lorca, one of Spain's most celebrated poets. The poems draw inspiration from the vibrant and tragic world of the Romani people, blending folkloric elements with profound themes of love, death, and cultural identity."
  },
  {
    "author": 'Gabriel García Márquez',
    "country": 'Colombia',
    "imageLink": 'images/one-hundred-years-of-solitude.jpg',
    "language": 'Spanish',
    "link": 'https://en.wikipedia.org/wiki/One_Hundred_Years_of_Solitude',
    "pages": 417,
    "title": 'One Hundred Years of Solitude',
    "year": 1967,
    "id": 34,
    "description": "Written by Gabriel García Márquez, 'One Hundred Years of Solitude' is a landmark novel in the genre of magical realism. It chronicles the Buendía family over multiple generations in the fictional town of Macondo, blending history, mythology, and vivid storytelling to explore themes of love, time, and the cyclical nature of human existence."
  },
  {
    "author": 'Gabriel García Márquez',
    "country": 'Colombia',
    "imageLink": 'images/love-in-the-time-of-cholera.jpg',
    "language": 'Spanish',
    "link": 'https://en.wikipedia.org/wiki/Love_in_the_Time_of_Cholera',
    "pages": 368,
    "title": 'Love in the Time of Cholera',
    "year": 1985,
    "id": 35,
    "description": "Penned by Gabriel García Márquez, 'Love in the Time of Cholera' is a poignant love story that spans several decades. Set in a fictional Caribbean town, the novel explores the enduring love between Florentino Ariza and Fermina Daza, examining themes of love, time, and the complexities of human relationships."
  },
  {
    "author": 'Johann Wolfgang von Goethe',
    "country": 'Saxe-Weimar',
    "imageLink": 'images/faust.jpg',
    "language": 'German',
    "link": 'https://en.wikipedia.org/wiki/Goethe%27s_Faust',
    "pages": 158,
    "title": 'Faust',
    "year": 1832,
    "id": 36,
    "description": "Written by Johann Wolfgang von Goethe, 'Faust' is a tragic play that tells the story of Dr. Faust, a scholar who makes a pact with the devil in exchange for unlimited knowledge and worldly pleasures. The play explores themes of ambition, temptation, and the consequences of selling one's soul for personal gain."
  },
  {
    "author": 'Nikolai Gogol',
    "country": 'Russia',
    "imageLink": 'images/dead-souls.jpg',
    "language": 'Russian',
    "link": 'https://en.wikipedia.org/wiki/Dead_Souls',
    "pages": 432,
    "title": 'Dead Souls',
    "year": 1842,
    "id": 37,
    "description": "Penned by Nikolai Gogol, 'Dead Souls' is a satirical novel that follows the adventures of Chichikov, a swindler who travels through the Russian countryside collecting 'dead souls'—the names of deceased serfs still counted on the census. The book provides a scathing critique of 19th-century Russian society and explores themes of greed, corruption, and moral decay."
  },
  {
    "author": 'Günter Grass',
    "country": 'Germany',
    "imageLink": 'images/the-tin-drum.jpg',
    "language": 'German',
    "link": 'https://en.wikipedia.org/wiki/The_Tin_Drum',
    "pages": 600,
    "title": 'The Tin Drum',
    "year": 1959,
    "id": 38,
    "description": "Written by Günter Grass, 'The Tin Drum' is a surreal and darkly comedic novel set in Danzig, Germany, before, during, and after World War II. The protagonist, Oskar Matzerath, decides to stop growing at the age of three and communicates through the beating of a tin drum. The book explores themes of history, identity, and the absurdity of human existence."
  },
  {
    "author": 'João Guimarães Rosa',
    "country": 'Brazil',
    "imageLink": 'images/the-devil-to-pay-in-the-backlands.jpg',
    "language": 'Portuguese',
    "link": 'https://en.wikipedia.org/wiki/The_Devil_to_Pay_in_the_Backlands',
    "pages": 494,
    "title": 'The Devil to Pay in the Backlands',
    "year": 1956,
    "id": 39,
    "description": "Also known as 'Grande Sertão: Veredas,' 'The Devil to Pay in the Backlands' is a novel by João Guimarães Rosa. It is set in the Brazilian backlands and narrated by Riobaldo, a bandit and adventurer. The book combines elements of folklore, philosophy, and regional dialects to explore themes of violence, love, and the search for meaning in a harsh and unforgiving landscape."
  },
  {
    "author": 'Knut Hamsun',
    "country": 'Norway',
    "imageLink": 'images/hunger.jpg',
    "language": 'Norwegian',
    "link": 'https://en.wikipedia.org/wiki/Hunger_(Hamsun_novel)',
    "pages": 176,
    "title": 'Hunger',
    "year": 1890,
    "id": 40,
    "description": "Written by Knut Hamsun, 'Hunger' is a novel that delves into the mind of an unnamed protagonist as he struggles with poverty, starvation, and his own deteriorating mental state in late 19th-century Oslo. The book offers a raw and introspective portrayal of human desperation and the lengths one can go to survive."
  },
  {
    "author": 'Ernest Hemingway',
    "country": 'United States',
    "imageLink": 'images/the-old-man-and-the-sea.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/The_Old_Man_and_the_Sea',
    "pages": 128,
    "title": 'The Old Man and the Sea',
    "year": 1952,
    "id": 41,
    "description": "Written by Ernest Hemingway, 'The Old Man and the Sea' is a novella that tells the story of an aging fisherman, Santiago, and his epic battle with a giant marlin in the Gulf Stream. The book explores themes of resilience, determination, and the complex relationship between humans and nature."
  },
  {
    "author": 'Homer',
    "country": 'Greece',
    "imageLink": 'images/the-iliad-of-homer.jpg',
    "language": 'Greek',
    "link": 'https://en.wikipedia.org/wiki/Iliad',
    "pages": 608,
    "title": 'Iliad',
    "year": -735,
    "id": 42,
    "description": "Attributed to the ancient Greek poet Homer, 'Iliad' is an epic poem that narrates the events of the Trojan War. Focusing on the wrath of Achilles, the poem explores themes of honor, heroism, fate, and the destructive consequences of war."
  },
  {
    "author": 'Homer',
    "country": 'Greece',
    "imageLink": 'images/the-odyssey-of-homer.jpg',
    "language": 'Greek',
    "link": 'https://en.wikipedia.org/wiki/Odyssey',
    "pages": 374,
    "title": 'Odyssey',
    "year": -800,
    "id": 43,
    "description": "Also attributed to Homer, the 'Odyssey' is an epic poem that follows the adventures of Odysseus as he attempts to return home after the Trojan War. The poem explores themes of heroism, temptation, fate, and the power of storytelling."
  },
  {
    "author": 'Henrik Ibsen',
    "country": 'Norway',
    "imageLink": 'images/a-Dolls-house.jpg',
    "language": 'Norwegian',
    "link": 'https://en.wikipedia.org/wiki/A_Doll%27s_House',
    "pages": 68,
    "title": "A Doll's House",
    "year": 1879,
    "id": 44,
    "description": "Written by Henrik Ibsen, 'A Doll's House' is a groundbreaking play that explores the role of women in society and issues of gender inequality. The play follows Nora Helmer, a seemingly happy wife and mother, as she confronts the limitations of her marriage and seeks self-discovery and independence."
  },
  {
    "author": 'James Joyce',
    "country": 'Irish Free State',
    "imageLink": 'images/ulysses.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/Ulysses_(novel)',
    "pages": 228,
    "title": 'Ulysses',
    "year": 1922,
    "id": 45,
    "description": "Written by James Joyce, 'Ulysses' is a modernist novel that follows the lives of Leopold Bloom and Stephen Dedalus over the course of a single day in Dublin, Ireland. The book employs stream-of-consciousness narrative techniques and dense symbolism to explore themes of identity, sexuality, religion, and the complexities of human experience."
  },
  {
    "author": 'Franz Kafka',
    "country": 'Czechoslovakia',
    "imageLink": 'images/stories-of-franz-kafka.jpg',
    "language": 'German',
    "link": 'https://en.wikipedia.org/wiki/Franz_Kafka_bibliography#Short_stories',
    "pages": 488,
    "title": 'Stories',
    "year": 1924,
    "id": 46,
    "description": "Written by Franz Kafka, 'The Trial' is a surreal and allegorical novel that follows the protagonist, Joseph K., as he is arrested and put on trial by a mysterious and oppressive bureaucracy. The book explores themes of guilt, alienation, and the absurdity of the legal system."
  },
  {
    "author": 'Franz Kafka',
    "country": 'Czechoslovakia',
    "imageLink": 'images/the-trial.jpg',
    "language": 'German',
    "link": 'https://en.wikipedia.org/wiki/The_Trial',
    "pages": 160,
    "title": 'The Trial',
    "year": 1925,
    "id": 47,
    "description": "Also written by Franz Kafka, 'The Castle' tells the story of K., a land surveyor who arrives in a village dominated by a mysterious castle. The novel explores themes of bureaucracy, power, and the futile search for meaning and acceptance in an opaque and oppressive social structure."
  },
  {
    "author": 'Franz Kafka',
    "country": 'Czechoslovakia',
    "imageLink": 'images/the-castle.jpg',
    "language": 'German',
    "link": 'https://en.wikipedia.org/wiki/The_Castle_(novel)',
    "pages": 352,
    "title": 'The Castle',
    "year": 1926,
    "id": 48,
    "description": "Written by Kalidasa, 'The recognition of Shakuntala' is a Sanskrit play that tells the story of King Dushyanta and Shakuntala, a young woman raised in a hermitage. The play explores themes of love, fate, and the tension between duty and personal desire."
  },
  {
    "author": 'Kālidāsa',
    "country": 'India',
    "imageLink": 'images/the-recognition-of-shakuntala.jpg',
    "language": 'Sanskrit',
    "link": 'https://en.wikipedia.org/wiki/Abhij%C3%B1%C4%81na%C5%9B%C4%81kuntalam',
    "pages": 147,
    "title": 'The recognition of Shakuntala',
    "year": 150,
    "id": 49,
    "description": "Written by Yasunari Kawabata, 'The Sound of the Mountain' is a novel that follows the life of Shingo, an elderly businessman, as he reflects on his family, marriage, and the passage of time. The book explores themes of love, regret, and the fragility of human relationships."
  },
  {
    "author": 'Yasunari Kawabata',
    "country": 'Japan',
    "imageLink": 'images/the-sound-of-the-mountain.jpg',
    "language": 'Japanese',
    "link": 'https://en.wikipedia.org/wiki/The_Sound_of_the_Mountain',
    "pages": 288,
    "title": 'The Sound of the Mountain',
    "year": 1954,
    "id": 50,
    "description": "Written by Nikos Kazantzakis, 'Zorba the Greek' is a novel that follows the narrator's encounter with Alexis Zorba, a charismatic and free-spirited Greek. The book explores themes of freedom, passion, and the contrast between intellectual pursuits and the pleasures of living in the moment."
  },
  {
    "author": 'Nikos Kazantzakis',
    "country": 'Greece',
    "imageLink": 'images/zorba-the-greek.jpg',
    "language": 'Greek',
    "link": 'https://en.wikipedia.org/wiki/Zorba_the_Greek',
    "pages": 368,
    "title": 'Zorba the Greek',
    "year": 1946,
    "id": 51,
    "description": "Written by D.H. Lawrence, 'Sons and Lovers' is a semi-autobiographical novel that delves into the complex relationships between the Morel family members, particularly the bond between Paul Morel and his possessive mother. The book explores themes of love, sexuality, and the struggle for self-identity."
  },
  {
    "author": 'D. H. Lawrence',
    "country": 'United Kingdom',
    "imageLink": 'images/sons-and-lovers.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/Sons_and_Lovers',
    "pages": 432,
    "title": 'Sons and Lovers',
    "year": 1913,
    "id": 52,
    "description": "Penned by Halldór Laxness, 'Independent People' is a novel set in rural Iceland and follows the life of Bjartur of Summerhouses, a sheep farmer who strives for independence and self-sufficiency. The book explores themes of resilience, isolation, and the hardships of rural life."
  },
  {
    "author": 'Halldór Laxness',
    "country": 'Iceland',
    "imageLink": 'images/independent-people.jpg',
    "language": 'Icelandic',
    "link": 'https://en.wikipedia.org/wiki/Independent_People',
    "pages": 470,
    "title": 'Independent People',
    "year": 1934,
    "id": 53,
    "description": "Written by Doris Lessing, 'The Golden Notebook' is a novel that explores the life of Anna Wulf, a writer who keeps four separate notebooks to document different aspects of her life. The book delves into themes of feminism, politics, and the complexities of personal and creative identity."
  },
  {
    "author": 'Giacomo Leopardi',
    "country": 'Italy',
    "imageLink": 'images/poems-giacomo-leopardi.jpg',
    "language": 'Italian',
    "link": '',
    "pages": 184,
    "title": 'Poems',
    "year": 1818,
    "id": 54,
    "description": "Written by Astrid Lindgren, 'Pippi Longstocking' is a beloved children's book that follows the adventures of Pippi Longstocking, a strong, independent, and unconventional young girl with superhuman strength. The book celebrates imagination, individuality, and the power of friendship."
  },
  {
    "author": 'Doris Lessing',
    "country": 'United Kingdom',
    "imageLink": 'images/the-golden-notebook.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/The_Golden_Notebook',
    "pages": 688,
    "title": 'The Golden Notebook',
    "year": 1962,
    "id": 55,
    "description": "Written by Lu Xun, 'Diary of a Madman' is a groundbreaking short story that critiques traditional Chinese society and its oppressive systems. The story is written in the form of a diary entry and follows the protagonist's descent into madness as he becomes increasingly aware of the cannibalistic nature of the society around him."
  },
  {
    "author": 'Astrid Lindgren',
    "country": 'Sweden',
    "imageLink": 'images/pippi-longstocking.jpg',
    "language": 'Swedish',
    "link": 'https://en.wikipedia.org/wiki/Pippi_Longstocking',
    "pages": 160,
    "title": 'Pippi Longstocking',
    "year": 1945,
    "id": 56,
    "description": "Also known as 'Children of the Alley,' 'Children of Gebelawi' is a novel by Naguib Mahfouz. The book depicts the lives of several generations in an Egyptian alley and explores themes of religion, power, and the cyclical nature of history."
  },
  {
    "author": 'Lu Xun',
    "country": 'China',
    "imageLink": 'images/diary-of-a-madman.jpg',
    "language": 'Chinese',
    "link": 'https://en.wikipedia.org/wiki/A_Madman%27s_Diary',
    "pages": 389,
    "title": 'Diary of a Madman',
    "year": 1918,
    "id": 57,
    "description": "Written by Thomas Mann, 'Buddenbrooks' is a novel that follows the decline of the Buddenbrook family, a wealthy and respected merchant family in 19th-century Lübeck, Germany. The book explores themes of family, tradition, and the changing social and economic landscape of the time."
  },
  {
    "author": 'Naguib Mahfouz',
    "country": 'Egypt',
    "imageLink": 'images/children-of-gebelawi.jpg',
    "language": 'Arabic',
    "link": 'https://en.wikipedia.org/wiki/Children_of_Gebelawi',
    "pages": 355,
    "title": 'Children of Gebelawi',
    "year": 1959,
    "id": 58,
    "description": "Also written by Thomas Mann, 'The Magic Mountain' is a philosophical novel set in a sanatorium in the Swiss Alps. The book follows the experiences of Hans Castorp, a young man who becomes embroiled in debates about life, mortality, and the nature of time during his extended stay at the sanatorium."
  },
  {
    "author": 'Thomas Mann',
    "country": 'Germany',
    "imageLink": 'images/buddenbrooks.jpg',
    "language": 'German',
    "link": 'https://en.wikipedia.org/wiki/Buddenbrooks',
    "pages": 736,
    "title": 'Buddenbrooks',
    "year": 1901,
    "id": 59,
    "description": "Written by Herman Melville, 'Moby Dick' is a classic novel that tells the story of Captain Ahab's obsessive quest to hunt down and kill the white whale, Moby Dick. The book explores themes of obsession, revenge, and the battle between man and nature."
  },
  {
    "author": 'Thomas Mann',
    "country": 'Germany',
    "imageLink": 'images/the-magic-mountain.jpg',
    "language": 'German',
    "link": 'https://en.wikipedia.org/wiki/The_Magic_Mountain',
    "pages": 720,
    "title": 'The Magic Mountain',
    "year": 1924,
    "id": 60,
    "description": "Written by Michel de Montaigne, 'Essays' is a collection of philosophical and personal reflections on various topics. Montaigne's essays cover a wide range of subjects, including friendship, education, ethics, and the nature of humanity."
  },
  {
    "author": 'Herman Melville',
    "country": 'United States',
    "imageLink": 'images/moby-dick.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/Moby-Dick',
    "pages": 378,
    "title": 'Moby Dick',
    "year": 1851,
    "id": 61,
    "description": "Written by Herodotus, 'History' is an ancient Greek work often considered the first work of history in Western literature. The book chronicles the Persian Wars between the Greeks and Persians, providing both historical accounts and cultural observations."
  },
  {
    "author": 'Michel de Montaigne',
    "country": 'France',
    "imageLink": 'images/essais.jpg',
    "language": 'French',
    "link": 'https://en.wikipedia.org/wiki/Essays_(Montaigne)',
    "pages": 404,
    "title": 'Essays',
    "year": 1595,
    "id": 62,
    "description": "Written by Toni Morrison, 'Beloved' is a powerful novel that explores the lasting impact of slavery and the trauma it inflicts on individuals and communities. Set in the aftermath of the American Civil War, the book follows Sethe, a former slave who is haunted by the memories of her past."
  },
  {
    "author": 'Elsa Morante',
    "country": 'Italy',
    "imageLink": 'images/history.jpg',
    "language": 'Italian',
    "link": 'https://en.wikipedia.org/wiki/History_(novel)',
    "pages": 600,
    "title": 'History',
    "year": 1974,
    "id": 63,
    "description": "Written by Murasaki Shikibu, 'The Tale of Genji' is a classic work of Japanese literature. It follows the life and romantic exploits of Prince Genji in the Heian period, exploring themes of love, courtly life, and the changing roles of women in society."
  },
  {
    "author": 'Toni Morrison',
    "country": 'United States',
    "imageLink": 'images/beloved.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/Beloved_(novel)',
    "pages": 321,
    "title": 'Beloved',
    "year": 1987,
    "id": 64,
    "description": "Written by Robert Musil, 'The Man Without Qualities' is a sprawling novel set in Vienna during the Austro-Hungarian Empire. The book explores the intellectual and moral crisis of Ulrich, a man who feels detached from society and struggles to find meaning in a rapidly changing world."
  },
  {
    "author": 'Murasaki Shikibu',
    "country": 'Japan',
    "imageLink": 'images/the-tale-of-genji.jpg',
    "language": 'Japanese',
    "link": 'https://en.wikipedia.org/wiki/The_Tale_of_Genji',
    "pages": 1360,
    "title": 'The Tale of Genji',
    "year": 1006,
    "id": 65,
    "description": "Written by Vladimir Nabokov, 'Lolita' is a controversial and highly acclaimed novel. The story is narrated by Humbert Humbert, a middle-aged man obsessed with a young girl named Lolita. The book delves into themes of desire, power, and the moral ambiguity of the protagonist."
  },
  {
    "author": 'Robert Musil',
    "country": 'Austria',
    "imageLink": 'images/the-man-without-qualities.jpg',
    "language": 'German',
    "link": 'https://en.wikipedia.org/wiki/The_Man_Without_Qualities',
    "pages": 365,
    "title": 'The Man Without Qualities',
    "year": 1931,
    "id": 66,
    "description": "Written by George Orwell, 'Nineteen Eighty-Four' is a dystopian novel that depicts a totalitarian society ruled by Big Brother, where individualism and independent thought are suppressed. The book explores themes of government surveillance, propaganda, and the manipulation of truth."
  },
  {
    "author": 'Vladimir Nabokov',
    "country": 'Russia/United States',
    "imageLink": 'images/lolita.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/Lolita',
    "pages": 317,
    "title": 'Lolita',
    "year": 1955,
    "id": 67,
    "description": "Written by Ovid, 'Metamorphoses' is a narrative poem that collects various myths and legends from Greek and Roman mythology. The book weaves together stories of transformation, love, and the workings of the divine."
  },
  {
    "author": 'George Orwell',
    "country": 'United Kingdom',
    "imageLink": 'images/nineteen-eighty-four.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/Nineteen_Eighty-Four',
    "pages": 272,
    "title": 'Nineteen Eighty-Four',
    "year": 1949,
    "id": 68,
    "description": "Written by Fernando Pessoa, 'The Book of Disquiet' is a fragmentary work that offers a collection of thoughts, reflections, and observations on life, art, and existence. The book reflects the author's introspective and melancholic worldview."
  },
  {
    "author": 'Ovid',
    "country": 'Roman Empire',
    "imageLink": 'images/the-metamorphoses-of-ovid.jpg',
    "language": 'Classical Latin',
    "link": 'https://en.wikipedia.org/wiki/Metamorphoses',
    "pages": 576,
    "title": 'Metamorphoses',
    "year": 100,
    "id": 69,
    "description": "Written by Edgar Allan Poe, 'Tales' is a collection of short stories that showcase Poe's mastery of the macabre and the psychological. The book includes iconic tales such as 'The Tell-Tale Heart,' 'The Fall of the House of Usher,' and 'The Murders in the Rue Morgue.'"
  },
  {
    "author": 'Fernando Pessoa',
    "country": 'Portugal',
    "imageLink": 'images/the-book-of-disquiet.jpg',
    "language": 'Portuguese',
    "link": 'https://en.wikipedia.org/wiki/The_Book_of_Disquiet',
    "pages": 272,
    "title": 'The Book of Disquiet',
    "year": 1928,
    "id": 70,
    "description": "Written by Marcel Proust, 'In Search of Lost Time' (also known as 'Remembrance of Things Past') is a monumental novel that explores memory, time, and the intricacies of human experience. The seven-volume work delves into the narrator's recollections of his past, his observations of society, and his reflections on art and love."
  },
  {
    "author": 'Edgar Allan Poe',
    "country": 'United States',
    "imageLink": 'images/tales-and-poems-of-edgar-allan-poe.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/Edgar_Allan_Poe_bibliography#Tales',
    "pages": 842,
    "title": 'Tales',
    "year": 1950,
    "id": 71,
    "description": "Written by François Rabelais, 'Gargantua and Pantagruel' is a satirical and picaresque series of novels that follow the adventures of the giant Gargantua and his son Pantagruel. The books offer a blend of ribald humor, social commentary, and philosophical digressions."
  },
  {
    "author": 'Marcel Proust',
    "country": 'France',
    "imageLink": 'images/a-la-recherche-du-temps-perdu.jpg',
    "language": 'French',
    "link": 'https://en.wikipedia.org/wiki/In_Search_of_Lost_Time',
    "pages": 2408,
    "title": 'In Search of Lost Time',
    "year": 1920,
    "id": 72,
    "description": "Written by Juan Rulfo, 'Pedro Páramo' is a novel set in rural Mexico and tells the story of Juan Preciado as he returns to his deceased mother's hometown and discovers the secrets and ghosts of the past. The book explores themes of memory, loss, and the impact of personal and collective history."
  },
  {
    "author": 'François Rabelais',
    "country": 'France',
    "imageLink": 'images/gargantua-and-pantagruel.jpg',
    "language": 'French',
    "link": 'https://en.wikipedia.org/wiki/Gargantua_and_Pantagruel',
    "pages": 623,
    "title": 'Gargantua and Pantagruel',
    "year": 1533,
    "id": 73,
    "description": "Written by Jalal ad-Din Muhammad Rumi, 'The Masnavi' is a poetic work that consists of spiritual teachings, anecdotes, and mystical stories. The book serves as a guide to the path of spiritual realization and union with the divine."
  },
  {
    "author": 'Juan Rulfo',
    "country": 'Mexico',
    "imageLink": 'images/pedro-paramo.jpg',
    "language": 'Spanish',
    "link": 'https://en.wikipedia.org/wiki/Pedro_P%C3%A1ramo',
    "pages": 124,
    "title": 'Pedro Páramo',
    "year": 1955,
    "id": 74,
    "description": "Written by Salman Rushdie, 'Midnight's Children' is a magical realist novel that follows the lives of a group of children born at the stroke of midnight on the day of India's independence from British rule. The book intertwines their personal stories with the larger historical events of post-colonial India."
  },
  {
    "author": 'Rumi',
    "country": 'Sultanate of Rum',
    "imageLink": 'images/the-masnavi.jpg',
    "language": 'Persian',
    "link": 'https://en.wikipedia.org/wiki/Masnavi',
    "pages": 438,
    "title": 'The Masnavi',
    "year": 1236,
    "id": 75,
    "description": "Written by Saadi Shirazi, 'Bostan' (which translates to 'The Orchard') is a poetic work that offers moral and practical wisdom through a collection of anecdotes, tales, and poetry. The book reflects on the nature of humanity, ethics, and the pursuit of a virtuous life."
  },
  {
    "author": 'Salman Rushdie',
    "country": 'United Kingdom, India',
    "imageLink": 'images/midnights-children.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/Midnight%27s_Children',
    "pages": 536,
    "title": "Midnight's Children",
    "year": 1981,
    "id": 76,
    "description": "Written by Tayeb Salih, 'Season of Migration to the North' is a novel that explores the cultural and psychological complexities of post-colonial Sudan. The book follows the protagonist, Mustafa Sa'eed, as he returns to his homeland after years of studying in England, and delves into themes of identity, power, and the legacy of colonialism."
  },
  {
    "author": 'Saadi',
    "country": 'Persia, Persian Empire',
    "imageLink": 'images/bostan.jpg',
    "language": 'Persian',
    "link": 'https://en.wikipedia.org/wiki/Bustan_(book)',
    "pages": 298,
    "title": 'Bostan',
    "year": 1257,
    "id": 77,
    "description": "Written by José Saramago, 'Blindness' is a novel set in an unnamed city where an epidemic of sudden blindness spreads. The book explores the breakdown of society and human morality in the face of a catastrophic event, delving into themes of power, fear, and the resilience of the human spirit."
  },
  {
    "author": 'Tayeb Salih',
    "country": 'Sudan',
    "imageLink": 'images/season-of-migration-to-the-north.jpg',
    "language": 'Arabic',
    "link": 'https://en.wikipedia.org/wiki/Season_of_Migration_to_the_North',
    "pages": 139,
    "title": 'Season of Migration to the North',
    "year": 1966,
    "id": 78,
    "description": "Written by William Shakespeare, 'Hamlet' is a tragedy that follows the eponymous Prince of Denmark as he seeks to avenge his father's murder. The play explores themes of revenge, madness, mortality, and the complexities of human nature."
  },
  {
    "author": 'José Saramago',
    "country": 'Portugal',
    "imageLink": 'images/blindness.jpg',
    "language": 'Portuguese',
    "link": 'https://en.wikipedia.org/wiki/Blindness_(novel)',
    "pages": 352,
    "title": 'Blindness',
    "year": 1995,
    "id": 79,
    "description": "Written by William Shakespeare, 'King Lear' is a tragedy that depicts the downfall of King Lear as he descends into madness and loses his kingdom. The play explores themes of family, power, and the consequences of unchecked ambition."
  },
  {
    "author": 'William Shakespeare',
    "country": 'England',
    "imageLink": 'images/hamlet.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/Hamlet',
    "pages": 432,
    "title": 'Hamlet',
    "year": 1603,
    "id": 80,
    "description": "Written by William Shakespeare, 'Othello' is a tragedy that tells the story of Othello, a Moorish general in the Venetian army, and his tragic downfall due to jealousy and manipulation. The play delves into themes of love, race, jealousy, and the destructive power of suspicion."
  },
  {
    "author": 'William Shakespeare',
    "country": 'England',
    "imageLink": 'images/king-lear.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/King_Lear',
    "pages": 384,
    "title": 'King Lear',
    "year": 1608,
    "id": 81,
    "description": "Written by Sophocles, 'Oedipus the King' is a Greek tragedy that follows the titular character's quest to uncover the truth about his identity and confront the tragic prophecy that he would kill his father and marry his mother. The play explores themes of fate, free will, and the limits of human knowledge."
  },
  {
    "author": 'William Shakespeare',
    "country": 'England',
    "imageLink": 'images/othello.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/Othello',
    "pages": 314,
    "title": 'Othello',
    "year": 1609,
    "id": 82,
    "description": "Written by Stendhal, 'The Red and the Black' is a novel set in 19th-century France and follows the ambitious Julien Sorel as he navigates the complex social and political landscape of the time. The book explores themes of ambition, love, and the tension between individual desires and societal expectations."
  },
  {
    "author": 'Sophocles',
    "country": 'Greece',
    "imageLink": 'images/oedipus-the-king.jpg',
    "language": 'Greek',
    "link": 'https://en.wikipedia.org/wiki/Oedipus_the_King',
    "pages": 88,
    "title": 'Oedipus the King',
    "year": -430,
    "id": 83,
    "description": "Written by Laurence Sterne, 'The Life And Opinions of Tristram Shandy' is a novel that takes an unconventional and humorous approach to storytelling. The book is a fictional autobiography of the eponymous character, but it digresses into various tangents, philosophical musings, and playful experiments with narrative structure."
  },
  {
    "author": 'Stendhal',
    "country": 'France',
    "imageLink": 'images/le-rouge-et-le-noir.jpg',
    "language": 'French',
    "link": 'https://en.wikipedia.org/wiki/The_Red_and_the_Black',
    "pages": 576,
    "title": 'The Red and the Black',
    "year": 1830,
    "id": 84,
    "description": "Written by Italo Svevo, 'Confessions of Zeno' is a novel presented as the diary of Zeno Cosini, a middle-aged man undergoing psychoanalysis. The book humorously explores Zeno's neuroticism, his attempts to quit smoking, and his reflections on life, love, and self-deception."
  },
  {
    "author": 'Laurence Sterne',
    "country": 'England',
    "imageLink": 'images/the-life-and-opinions-of-tristram-shandy.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/The_Life_and_Opinions_of_Tristram_Shandy,_Gentleman',
    "pages": 640,
    "title": 'The Life And Opinions of Tristram Shandy',
    "year": 1760,
    "id": 85,
    "description": "Written by Jonathan Swift, 'Gulliver's Travels' is a satirical novel that follows the voyages of Lemuel Gulliver to various fantastical lands. Through his encounters with different societies, Swift criticizes human nature, politics, and social institutions, using humor and irony to convey his social commentary."
  },
  {
    "author": 'Italo Svevo',
    "country": 'Italy',
    "imageLink": 'images/confessions-of-zeno.jpg',
    "language": 'Italian',
    "link": 'https://en.wikipedia.org/wiki/Zeno%27s_Conscience',
    "pages": 412,
    "title": 'Confessions of Zeno',
    "year": 1923,
    "id": 86,
    "description": "Written by Leo Tolstoy, 'War and Peace' is an epic novel that chronicles the lives of several Russian aristocratic families against the backdrop of the Napoleonic Wars. The book explores themes of love, war, history, and the search for meaning in life."
  },
  {
    "author": 'Jonathan Swift',
    "country": 'Ireland',
    "imageLink": 'images/gullivers-travels.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/Gulliver%27s_Travels',
    "pages": 178,
    "title": "Gulliver's Travels",
    "year": 1726,
    "id": 87,
    "description": "Written by Leo Tolstoy, 'Anna Karenina' is a novel that tells the story of Anna Karenina, a married woman who embarks on an adulterous affair with Count Vronsky. The book explores themes of love, infidelity, societal expectations, and the consequences of one's choices."
  },
  {
    "author": 'Leo Tolstoy',
    "country": 'Russia',
    "imageLink": 'images/war-and-peace.jpg',
    "language": 'Russian',
    "link": 'https://en.wikipedia.org/wiki/War_and_Peace',
    "pages": 1296,
    "title": 'War and Peace',
    "year": 1867,
    "id": 88,
    "description": "Written by Leo Tolstoy, 'The Death of Ivan Ilyich' is a novella that explores the existential crisis of Ivan Ilyich, a high-ranking Russian official, as he grapples with his mortality. The book examines themes of death, the nature of life, and the pursuit of true happiness."
  },
  {
    "author": 'Leo Tolstoy',
    "country": 'Russia',
    "imageLink": 'images/anna-karenina.jpg',
    "language": 'Russian',
    "link": 'https://en.wikipedia.org/wiki/Anna_Karenina',
    "pages": 864,
    "title": 'Anna Karenina',
    "year": 1877,
    "id": 89,
    "description": "Written by Mark Twain, 'The Adventures of Huckleberry Finn' is a classic American novel that follows the journey of Huck Finn, a young boy, and Jim, an escaped slave, as they travel down the Mississippi River. The book addresses themes of racism, freedom, and the moral growth of its young protagonist."
  },
  {
    "author": 'Leo Tolstoy',
    "country": 'Russia',
    "imageLink": 'images/the-death-of-ivan-ilyich.jpg',
    "language": 'Russian',
    "link": 'https://en.wikipedia.org/wiki/The_Death_of_Ivan_Ilyich',
    "pages": 92,
    "title": 'The Death of Ivan Ilyich',
    "year": 1886,
    "id": 90,
    "description": "The 'Ramayana' is an ancient Indian epic attributed to the sage Valmiki. It tells the story of Prince Rama and his quest to rescue his wife, Sita, from the demon king Ravana. The epic explores themes of honor, devotion, righteousness, and the triumph of good over evil."
  },
  {
    "author": 'Mark Twain',
    "country": 'United States',
    "imageLink": 'images/the-adventures-of-huckleberry-finn.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/Adventures_of_Huckleberry_Finn',
    "pages": 224,
    "title": 'The Adventures of Huckleberry Finn',
    "year": 1884,
    "id": 91,
    "description": "Written by Virgil, 'The Aeneid' is an epic poem that follows the Trojan hero Aeneas as he journeys from the fall of Troy to the founding of Rome. The poem explores themes of destiny, heroism, and the relationship between gods and mortals."
  },
  {
    "author": 'Valmiki',
    "country": 'India',
    "imageLink": 'images/ramayana.jpg',
    "language": 'Sanskrit',
    "link": 'https://en.wikipedia.org/wiki/Ramayana',
    "pages": 152,
    "title": 'Ramayana',
    "year": -450,
    "id": 92,
    "description": "The 'Mahabharata' is an ancient Indian epic attributed to the sage Vyasa. It narrates the epic conflict between two branches of a royal family, the Pandavas and the Kauravas, and explores complex themes such as duty, morality, honor, and the nature of power."
  },
  {
    "author": 'Virgil',
    "country": 'Roman Empire',
    "imageLink": 'images/the-aeneid.jpg',
    "language": 'Classical Latin',
    "link": 'https://en.wikipedia.org/wiki/Aeneid',
    "pages": 442,
    "title": 'The Aeneid',
    "year": -23,
    "id": 93,
    "description": "Written by Walt Whitman, 'Leaves of Grass' is a collection of poetry that celebrates the beauty of the individual, nature, and the democratic spirit of America. The book showcases Whitman's lyrical and free verse style, as well as his bold exploration of themes of identity, sexuality, and spirituality."
  },
  {
    "author": 'Vyasa',
    "country": 'India',
    "imageLink": 'images/the-mahab-harata.jpg',
    "language": 'Sanskrit',
    "link": 'https://en.wikipedia.org/wiki/Mahabharata',
    "pages": 276,
    "title": 'Mahabharata',
    "year": -700,
    "id": 94,
    "description": "Written by Virginia Woolf, 'Mrs Dalloway' is a modernist novel that takes place over the course of a single day in the life of Clarissa Dalloway, an upper-class woman in post-World War I London. The book delves into themes of time, memory, identity, and the impact of social conventions on individuals."
  },
  {
    "author": 'Walt Whitman',
    "country": 'United States',
    "imageLink": 'images/leaves-of-grass.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/Leaves_of_Grass',
    "pages": 152,
    "title": 'Leaves of Grass',
    "year": 1855,
    "id": 95,
    "description": "Written by Virginia Woolf, 'To the Lighthouse' is a novel that explores the inner lives and relationships of the Ramsay family during their visits to the Isle of Skye. The book delves into themes of perception, memory, gender roles, and the passage of time."
  },
  {
    "author": 'Virginia Woolf',
    "country": 'United Kingdom',
    "imageLink": 'images/mrs-dalloway.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/Mrs_Dalloway',
    "pages": 216,
    "title": 'Mrs Dalloway',
    "year": 1925,
    "id": 96,
    "description": "Written by Virginia Woolf, 'To the Lighthouse' is a novel that explores the inner lives and relationships of the Ramsay family during their visits to the Isle of Skye. The book delves into themes of perception, memory, gender roles, and the passage of time."

  },
  {
    "author": 'Virginia Woolf',
    "country": 'United Kingdom',
    "imageLink": 'images/to-the-lighthouse.jpg',
    "language": 'English',
    "link": 'https://en.wikipedia.org/wiki/To_the_Lighthouse',
    "pages": 209,
    "title": 'To the Lighthouse',
    "year": 1927,
    "id": 97,
    "description": "Written by Marguerite Yourcenar, 'Memoirs of Hadrian' is a historical novel presented as the reflections of the Roman emperor Hadrian on his life, achievements, and the decline of the Roman Empire. The book offers a fictionalized account of Hadrian's experiences and insights into power, philosophy, and the complexities of ruling."

  },
  {
    "author": 'Marguerite Yourcenar',
    "country": 'France/Belgium',
    "imageLink": 'images/memoirs-of-hadrian.jpg',
    "language": 'French',
    "link": 'https://en.wikipedia.org/wiki/Memoirs_of_Hadrian',
    "pages": 408,
    "title": 'Memoirs of Hadrian',
    "year": 1951,
    "id": 98,
    "description": "Written by Marguerite Yourcenar, 'Memoirs of Hadrian' is a historical novel presented as the reflections of the Roman emperor Hadrian on his life, achievements, and the decline of the Roman Empire. The book offers a fictionalized account of Hadrian's experiences and insights into power, philosophy, and the complexities of ruling."


  }
]




export default Books